### ISSUE TITLE
Export does not reset Counter with DeltaTemporality

### ISSUE THREAD

**Issue by mingh2** [open-telemetry/opentelemetry-go#3136] opened 2022-09-01 22:30 UTC
### Description

Expect each export would reset the Counter with DeltaTemporality so that next export would only report the counters cumulated in that export period. However, it seems that the counter is never reset as if it was cumulative temporality.

### Environment

Go version 1.18
go.opentelemetry.io/otel v1.9.0
go.opentelemetry.io/otel/exporters/otlp/otlpmetric v0.31.0
go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v0.31.0
go.opentelemetry.io/otel/metric v0.31.0
go.opentelemetry.io/otel/sdk/metric v0.31.0

### Steps To Reproduce

Setup
```
client := otlpmetricgrpc.NewClient(otlpmetricgrpc.WithGRPCConn(conn))
exp, err := otlpmetric.New(
	ctx,
	client,
	otlpmetric.WithMetricAggregationTemporalitySelector(aggregation.DeltaTemporalitySelector()),
)

pusher := controller.New(
	processor.NewFactory(
		simple.NewWithHistogramDistribution(),
		exp,
	),
	controller.WithExporter(exp),
        controller.WithCollectPeriod(2*time.Second),
)

global.SetMeterProvider(pusher)
```

Count
```
m := global.Meter("ming.com/observ")
counter, err := m.SyncFloat64().Counter("job-total")

for i := 0; i < count; i++ {
	counter.Add(ctx, 1)
}
```

Sample Logs from logging exporter in OTEL collector
```
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope ming.com/observ
Metric #0
Descriptor:
     -> Name: job-total
     -> Description:
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_DELTA
NumberDataPoints #0
StartTimestamp: 2022-09-01 22:18:45.926849756 +0000 UTC
Timestamp: 2022-09-01 22:26:41.935199254 +0000 UTC
Value: **4736.000000**
	{"kind": "exporter", "data_type": "metrics", "name": "logging"}
2022-09-01T22:26:43.936Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 1}
2022-09-01T22:26:43.936Z	info	ResourceMetrics #0
Resource SchemaURL: https://opentelemetry.io/schemas/1.12.0
Resource labels:
     -> service.name: STRING(unknown_service:backend)
     -> telemetry.sdk.language: STRING(go)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(1.9.0)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope ming.com/observ
Metric #0
Descriptor:
     -> Name: job-total
     -> Description:
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_DELTA
NumberDataPoints #0
StartTimestamp: 2022-09-01 22:18:45.926849756 +0000 UTC
Timestamp: 2022-09-01 22:26:43.935167463 +0000 UTC
Value: **4756.000000**
```

Notice that the value is not reset and we continue to use the same start timestamp.

### Expected behavior

Expect the counter is reset and the startime fast forward to the export time. Did I miss anything?

**Comment by MrAlias** [comment] 2022-10-20 23:12
This should be resolved with the new metric SDK. Please reopen if you find otherwise.

**Comment by rami-dabain** [comment] 2023-11-11 23:04
Still the same in 
```
        go.opentelemetry.io/otel v1.20.0
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v0.43.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.20.0
	go.opentelemetry.io/otel/sdk v1.20.0
	go.opentelemetry.io/otel/sdk/metric v1.20.0
	go.opentelemetry.io/otel/trace v1.20.0
```


```
	exp, _ := otlpmetricgrpc.New(ctx, otlpmetricgrpc.WithGRPCConn(conn),
		otlpmetricgrpc.WithTemporalitySelector(deltaSelector))
        mr := metric.NewPeriodicReader(exp, metric.WithInterval(time.Second*15))
        mp := metric.NewMeterProvider(
		metric.WithResource(res),
		metric.WithReader(mr),
	)
	otel.SetMeterProvider(mp)
```
(no errors)

**Comment by scorpionknifes** [comment] 2023-12-19 04:34
I cannot reproduce this on otel `v1.20.0` or `v1.21.0`

I called the following twice
```
counter, _ := meter.Float64Counter("test_counter")
for i := 0; i < 10000; i++ {
    counter.Add(ctx, 1)
}
```
Working as expected - the value reset and we use the previous timestamp as start timestamp.
```
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope demo-server-meter 
Metric #0
Descriptor:
     -> Name: test_counter
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Delta
NumberDataPoints #0
StartTimestamp: 2023-12-19 04:32:22.379319 +0000 UTC
Timestamp: 2023-12-19 04:32:24.379277 +0000 UTC
Value: 10000.000000
	{"kind": "exporter", "data_type": "metrics", "name": "logging"}
2023-12-19T04:32:26.511Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "resource metrics": 1, "metrics": 1, "data points": 1}
2023-12-19T04:32:26.511Z	info	ResourceMetrics #0
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope demo-server-meter 
Metric #0
Descriptor:
     -> Name: test_counter
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Delta
NumberDataPoints #0
StartTimestamp: 2023-12-19 04:32:24.379277 +0000 UTC
Timestamp: 2023-12-19 04:32:26.37921 +0000 UTC
Value: 10000.000000
	{"kind": "exporter", "data_type": "metrics", "name": "logging"}
2023-12-19T04:32:27.112Z	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "resource metrics": 1, "metrics": 16, "data points": 18}
2023-12-19T04:32:27.113Z	info	ResourceMetrics #0
```

**Closed** 2023-12-19 07:30 UTC
Labels: bug, pkg:SDK, area:metrics
