### ISSUE TITLE
Regression: Delegation broken for global meterproviders

### ISSUE THREAD

**Issue by dashpole** [open-telemetry/opentelemetry-go#5827] opened 2024-09-17 13:55 UTC
From https://github.com/open-telemetry/opentelemetry-go/issues/5753#issuecomment-2354164595 reported by @Jesse-Bonfire

> It appears that this change has broken metrics that are registered before otel.SetMeterProvider is called. We are getting into a spot where the delegate on the siUpDownCounter isn't getting set as it looks like with the new map we are creating new ones and throwing away the old. But the old counter has been registered with meter.RegisterCallback
https://github.com/open-telemetry/opentelemetry-go/blob/42fd8fe325c125a40a21796c3f14b599e5e5f586/internal/global/meter.go#L175C8-L175C9

> I am pretty new to Otel and Go but this change seems to break the connection pools convention outlined here.
https://github.com/open-telemetry/semantic-conventions/blob/422eeb71f40c73d1b195723cc1cffeb09abf2391/docs/database/database-metrics.md#connection-pools

> Currently I am seeing this when instrumenting a Redis Cluster as it creates instrumentation for the connection pool to each node in the cluster. https://github.com/redis/go-redis/blob/233f97accde15bcb2e3d86ee744109b4dce34171/extra/redisotel/metrics.go#L85

> This problem is removed if we apply the instrumentation after we call otel.SetMeterProvider because the delegate just creates the counter. Not sure the best way to proceed.

> I am able to reproduce the exception with the following test case

```golang
package bench

import (
	"context"
	"testing"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
)

const (
	meterName  = "foo"
	metricName = "bar"
)

func BenchmarkSimple(b *testing.B) {
	b.ReportAllocs()
	meter := otel.Meter(meterName)
	for i := 0; i < 5; i++ {
		m, _ := meter.Int64ObservableUpDownCounter(metricName)
		meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
			o.ObserveInt64(m, int64(10))
			return nil
		}, m)
	}
	p1 := sdkmetric.NewMeterProvider()
	otel.SetMeterProvider(p1)
}
```

**Comment by Jesse-Bonfire** [comment] 2024-09-17 16:08
I think that I have a fix but I don't know the underlying intention to know if it is the correct way to solve the problem. I will post a PR in a few hours so there can be some discussion.

**Comment by MrAlias** [comment] 2024-09-28 14:39
This looks like a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/5852

**Comment by jmacd** [comment] 2024-10-09 22:34
I am not convinced that the test for this fix in #5828 is completely functional. I will present the evidence in this issue.

**Comment by jmacd** [comment] 2024-10-09 22:37
Note that the in internal/global/meter.go, there is an interface named `wrapped` with an `unwrap()` method.
https://github.com/open-telemetry/opentelemetry-go/blob/64416533d5cc340a8cc53d98084604758283af09/internal/global/meter.go#L490

Note that in instruments.go, there is an interface named `unwrapper` with an `Unwrap()` method.
https://github.com/open-telemetry/opentelemetry-go/blob/64416533d5cc340a8cc53d98084604758283af09/internal/global/instruments.go#L16

**Comment by jmacd** [comment] 2024-10-10 15:45
I have a test to reproduce the problem. At this point, I have confirmed that #5828 addressed a crash, but it does not address the feature which allows delegation to an alternative metric SDK.

**Comment by jmacd** [comment] 2024-10-10 23:09
False alarm. See https://github.com/open-telemetry/opentelemetry-go/pull/5881#issuecomment-2406192917

**Closed by jmacd** 2024-10-10 23:09 UTC
Labels: bug
