### ISSUE TITLE
OTEL exporter not working 

### ISSUE THREAD

**Issue by sanjaygopinath89** [open-telemetry/opentelemetry-go#911] opened 2020-07-06 22:07 UTC
Hi Team,

I and trying to implement a sample OTEL exporter to send traces to collector , then from there to Jaeger.

I following the example given in https://github.com/open-telemetry/opentelemetry-go/tree/master/example/otel-collector.

Steps followed
1. Downloaded  the repo git@github.com:open-telemetry/opentelemetry-go.git
2. In  https://github.com/open-telemetry/opentelemetry-go/blob/master/example/otel-collector/main.go  changed the collector endpoint "localhost:30080" to my collector ip and port <my_server_ip>:55680 where by OTLP receiver is enabled.
3. build and run the project 
4. **Expected to see the trace data in collector (since in collector exporter logging debug is enabled ), but i was not able to see it** .

The output i got when i run the script 

 ```
otel-collector % ./otel-collector 
2020/07/06 14:39:58 Waiting for connection...
2020/07/06 14:39:58 Doing really hard work (1 / 10)
2020/07/06 14:39:59 Doing really hard work (2 / 10)
2020/07/06 14:40:00 rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.metrics.v1.MetricsService
2020/07/06 14:40:00 Doing really hard work (3 / 10)
2020/07/06 14:40:01 Doing really hard work (4 / 10)
2020/07/06 14:40:02 exporter disconnected
2020/07/06 14:40:02 Doing really hard work (5 / 10)
2020/07/06 14:40:03 Doing really hard work (6 / 10)
2020/07/06 14:40:04 exporter disconnected
2020/07/06 14:40:04 Doing really hard work (7 / 10)
2020/07/06 14:40:05 Doing really hard work (8 / 10)
2020/07/06 14:40:06 exporter disconnected
2020/07/06 14:40:06 Doing really hard work (9 / 10)
2020/07/06 14:40:07 Doing really hard work (10 / 10)
2020/07/06 14:40:08 exporter disconnected
2020/07/06 14:40:08 Done!
2020/07/06 14:40:08 exporter disconnected
```

I have tried some other cases of open-telemetry which is working 
1. Tried to send trace data to Jeager using Jeager exporter (in golang itself ), i followed this example https://github.com/open-telemetry/opentelemetry-go/tree/master/example/jaeger and it is working . I can see the data in Jeager.
2. I have some sample apps which is created in Python and sending data to the same collector using OTLP exporter in python and i am able to see the data in collector and in Jeager also.

Since collector is able to get data from other sources , its not a collector configuration issue. Any other changes i need to make  to get it working ..?

**Comment by nilebox** [comment] 2020-07-07 00:23
@sanjaygopinath89 this might be a duplicate of #874 - which releases of Go SDK and Collector are you using?

**Comment by gunsluo** [comment] 2020-07-07 07:14
Hi, @sanjaygopinath89 
The example uses the configuration of version `0.3.0` collector.  

I use the following package and working fine.
```
        go.opentelemetry.io/collector v0.5.0
	go.opentelemetry.io/otel v0.7.0
	go.opentelemetry.io/otel/exporters/otlp v0.7.0
```

0.5.0 collector's config
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:55679"

processors:
  batch:
  queued_retry:

extensions:
  health_check: {}

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: example
    const_labels:
      label1: test
  logging:
      loglevel: debug

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [jaeger]

    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging]
```

**Comment by Aneurysm9** [comment] 2020-07-07 15:14
@gunsluo is correct.  The OTLP protocol definition had a BC breaking change that was incorporated in v0.7.0 of the SDK and v0.5.0 of the collector.  I've created #915 to update the example to use the correct version of the collector.

**Comment by MrAlias** [comment] 2020-07-07 17:27
@gunsluo please reopen if the merged PR doesn't fix things for you.

**Closed** 2020-07-07 17:26 UTC
Labels: area: example, area: exporter, bug

**Comment by sanjaygopinath89** [comment] 2020-07-07 20:14
@nilebox @gunsluo I updated my collector version to 0.5.0 and changed the collector package version also to 0.5.0, and it started working . 

Thanks for your response
