### ISSUE TITLE
Error when detecting from env with only OTEL_SERVICE_NAME specified

### ISSUE THREAD

**Issue by maxifom** [open-telemetry/opentelemetry-go#2207] opened 2021-08-29 16:52 UTC
### Description

When OTEL_SERVICE_NAME defined, but not OTEL_RESOURCE_ATTRIBUTES, error is received when detecting from env

### Environment

- OS: Ubuntu 21.04
- Architecture: x86
- Go Version: 1.17
- opentelemetry-go version: v1.0.0-RC2

### Steps To Reproduce

1. define env OTEL_SERVICE_NAME
2. Run program with metric
3. shows error in log: detecting resources: [partial resource: missing value: []]

### Expected behavior

when OTEL_SERVICE_NAME defined, but not OTEL_RESOURCE_ATTRIBUTES, see no error.

**Comment by MrAlias** [comment] 2021-08-30 14:58
Thanks for the bug report and your interest in the project! Can you update your "Steps To Reproduce" so others are able to start from a checked out version of this repository and reproduce the error? Also, can you share the full error? It will be impossible to troubleshoot this without more information about the issue.

**Comment by maxifom** [comment] 2021-09-01 09:40
Repo for bug reproduce: https://github.com/maxifom/opentelemetry-read-from-env-error-log

The error in the Steps to Reproduce is a full error

**Comment by MrAlias** [comment] 2021-09-03 15:11
Thanks for the info! This looks like a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/2138. It has been resolved in https://github.com/open-telemetry/opentelemetry-go/pull/2139. We are in the process of making another release that will include this fix. It should be out today or next week. Otherwise, you can use the main branch which includes the fix. Hopefully this helps.

**Closed by MrAlias** 2021-09-03 15:11 UTC
Labels: bug, area:resources
