### ISSUE TITLE
Adding Link from an existing context is too verbose, some helper would be appreciated.

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#2067] opened 2021-07-05 22:41 UTC
### Problem Statement

Right now to create a Link from a context I have to:

```golang
	trace.WithLinks(trace.Link{
		SpanContext: trace.SpanContextFromContext(ctx),
	}
```

### Proposed Solution

```golang
	trace.WithLinks(trace.LinkFromContext(ctx))
```

maybe even better

```
	trace.WithLinksFromContext(ctx)
```

**Comment by MrAlias** [comment] 2021-07-08 15:22
I'm in favor of

- `trace.WithLinksFromContext(ctx)`
- `trace.WithLinkedContext(ctx)`
- `trace.WithContextLink(ctx)`

**Comment by lastchiliarch** [comment] 2021-07-15 14:31
I'm prefer trace.WithLinks(trace.LinkFromContext(ctx)) to trace.WithContextLink(ctx).
I think trace.WithLinks is easy to use when we have a link to add, but create a link from context is a little verbose.

**Comment by MrAlias** [comment] 2021-07-22 14:13
Adding to the SIG agenda for today to get more feedback.

**Comment by MrAlias** [comment] 2021-07-22 14:19
Looking closer this might now be a duplicate of #2068 (?) which has a proposed solution in #2115.

**Closed** 2021-07-22 18:39 UTC
Labels: enhancement
