### ISSUE TITLE
Remove `trace.WithRecord()` trace start option

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#787] opened 2020-06-02 15:41 UTC
The spec: 
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#isrecording

Some history:
https://github.com/open-telemetry/opentelemetry-go/pull/223
#188 
https://github.com/open-telemetry/opentelemetry-go/issues/192

The task is to implement `Span.IsRecording() bool` which returns true if the span is not a no-op.

**Comment by evantorrie** [comment] 2020-06-08 18:39
@jmacd Can you clarify this a little? I thought #188 did change/add the `IsRecording() bool` function to the Span interface and all implementations.

**Comment by jmacd** [comment] 2020-06-08 20:09
I realize that `IsRecording()` is implemented. I thought it had been removed.

**Comment by jmacd** [comment] 2020-06-08 20:10
Ah, the spec does not support a `WithRecord()` function that we currently have. It's the sampler's responsibility for deciding if a span records.

**Comment by MrAlias** [comment] 2020-09-25 19:42
I think this has become a duplicate of #192, going to close this and consolidate the conversation there.

**Closed by MrAlias** 2020-09-25 19:42 UTC
Labels: area:trace, blocked:specification
