### ISSUE TITLE
Can't export attributes with the GRPC exporter

### ISSUE THREAD

**Issue by hush-hush** [open-telemetry/opentelemetry-go#2112] opened 2021-07-21 16:56 UTC
### Description

I'm trying to send metrics with attribute attache to it. When using the stdout exporter the attributes are shown correctly. But when using the GRPC exporter and the open-telemetry collector I no longer see them.

The test code is pasted at the end, I'm sending 1 metric `test_metric` with 1 attribute `attr=test`.

Example of the stdout exporter output, showing my tag:
```
[
	{
		"Name": "test_metric{service.name=unknown_service:test,telemetry.sdk.language=go,telemetry.sdk.name=opentelemetry,telemetry.sdk.version=1.0.0-RC1,instrumentation.name=go-otel-test,attr=test}",
		"Sum": 10
	}
]
```

When using the official `otel/opentelemetry-collector-contrib` container with this config:
```
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  logging:
    loglevel: debug

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, logging]
```

I don't have any tags  in the prometheus output nor the logging one:
```
# HELP test_metric 
# TYPE test_metric counter
test_metric 0
```

Thanks for the help and answer !

### Environment

- OS: linux (debian 11) and docker
- Architecture: x86
- Go Version: go1.15.13
- opentelemetry-go version (from go.mod): 
```
go.opentelemetry.io/otel v1.0.0-RC1
go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v0.22.0
go.opentelemetry.io/otel/exporters/stdout/stdoutmetric v0.22.0
```

### Steps To Reproduce

Here is the test code to reproduce:
```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	"go.opentelemetry.io/otel/exporters/stdout/stdoutmetric"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/global"
	export "go.opentelemetry.io/otel/sdk/export/metric"
	controller "go.opentelemetry.io/otel/sdk/metric/controller/basic"
	processor "go.opentelemetry.io/otel/sdk/metric/processor/basic"
	"go.opentelemetry.io/otel/sdk/metric/selector/simple"
	"google.golang.org/grpc"
)

func main() {
	ctx := context.Background()
	var exporter export.Exporter
	var err error

	if os.Getenv("OTLP_GRPC") != "" {
		exporter, err = otlpmetricgrpc.New(
			ctx,
			otlpmetricgrpc.WithInsecure(),
			otlpmetricgrpc.WithEndpoint("127.0.0.1:4317"),
			otlpmetricgrpc.WithDialOption(grpc.WithBlock()),
		)
		if err != nil {
			log.Fatalf("failed to initialize grpc exporter: %s", err)
		}
	} else {
		exporter, err = stdoutmetric.New(stdoutmetric.WithPrettyPrint())
		if err != nil {
			log.Fatal(fmt.Errorf("error creating stdout exporter: %s", err))
		}
	}
	pusher := controller.New(
		processor.New(
			simple.NewWithInexpensiveDistribution(),
			exporter,
		),
		controller.WithExporter(exporter),
		controller.WithCollectPeriod(2*time.Second),
	)

	err = pusher.Start(ctx)
	if err != nil {
		log.Fatalf("failed to initialize pusher: %s", err)
	}
	defer func() { _ = pusher.Stop(ctx) }()

	meterProvider := pusher.MeterProvider()
	global.SetMeterProvider(meterProvider)
	meter := meterProvider.Meter("go-otel-test")

	m := metric.Must(meter).NewInt64Counter("test_metric").Bind(attribute.String("attr", "test"))

	for {
		m.Add(ctx, 1)
		time.Sleep(200 * time.Millisecond)
	}
}
```

The docker line for the collector:
```
docker run --rm -ti -v "${PWD}/otel-local-config.yaml":/otel-local-config.yaml otel/opentelemetry-collector-contrib --config otel-local-config.yam
```

and then just curling the prometheus endpoint with `curl -s "http://127.0.0.1:8889/metrics"`

### Expected behavior

I would have expected to see my label exported to prometheus and other exporters (I tried the Datadog exporter with the same result).

such as:
```
# HELP test_metric 
# TYPE test_metric counter
test_metric{attr="test"} 0
```

**Comment by shaneing** [comment] 2021-07-26 08:43
I have another problem, the counter is automatically reset to 0 after exporting.

**Comment by Aneurysm9** [comment] 2021-07-30 22:38
I suspect this is related to the collector being in the process of updating to the current OTLP proto.  Metric labels were renamed to attributes for consistency in OTLP v0.9.  This SDK has updated and made that change, but the collector has not yet.  https://github.com/open-telemetry/opentelemetry-collector/issues/3535 is the issue to watch.

**Comment by zhyChesterCheung** [comment] 2021-09-02 12:28
I've noticed this issue has been done in [#3805](https://github.com/open-telemetry/opentelemetry-collector/pull/3805), and I can't reproduce this problem. So we could just close this issue.

**Comment by MrAlias** [comment] 2021-10-15 22:12
> I've noticed this issue has been done in [#3805](https://github.com/open-telemetry/opentelemetry-collector/pull/3805), and I can't reproduce this problem. So we could just close this issue.

@hush-hush please reopen if you find this to not be resolved.

**Closed by MrAlias** 2021-10-15 22:12 UTC
Labels: bug, area:metrics, pkg:exporter:otlp
