### ISSUE TITLE
Issues using metrics + OTEL collector + prometheus exporter

### ISSUE THREAD

**Issue by firefixmaarten** [open-telemetry/opentelemetry-go#886] opened 2020-07-02 07:56 UTC
using:
the go.opentelemetry.io/otel 0.7.0 package
the otel collector 0.5.0 as receiver:
```
otlp/staging:
  protocols:
    grpc:
      endpoint: 0.0.0.0:55681
exporters:
  prometheus/staging:
    endpoint: "0.0.0.0:8890"
service:
  pipelines:
    metrics/staging:
      receivers: [otlp/staging]
      exporters: [prometheus/staging]
```
```
import (
	"context"
	"fmt"
	"time"

	"github.com/firefixmaarten/test-otel/metrics"
	"go.opentelemetry.io/otel/api/global"
	"go.opentelemetry.io/otel/api/kv"
	"go.opentelemetry.io/otel/api/metric"
	"go.opentelemetry.io/otel/exporters/otlp"
	"go.opentelemetry.io/otel/sdk/metric/controller/push"
	"go.opentelemetry.io/otel/sdk/metric/selector/simple"
)

func installNewPipeline(options ...push.Option) (*push.Controller, error) {
	controller, err := newExportPipeline(options...)
	if err != nil {
		return controller, err
	}
	global.SetMeterProvider(controller.Provider())
	return controller, err
}

func newExportPipeline(options ...push.Option) (*push.Controller, error) {
	exp, err := otlp.NewExporter(
		otlp.WithInsecure(),
		otlp.WithAddress("127.0.0.1:55681"),
	)
	if err != nil {
		return nil, err
	}

	pusher := push.New(
		simple.NewWithExactDistribution(),
		exp,
		append([]push.Option{push.WithPeriod(time.Duration(3) * time.Second)}, options...)...,
	)
	pusher.Start()

	return pusher, nil
}
func main() {
	pipeline, err := installNewPipeline()
	if err != nil {
		fmt.Printf("%s", err)
	}
	defer pipeline.Stop()

	metricCreatedBagsTotal := metric.Must(global.Meter("esoptra/pluglet-golang-zaza")).NewFloat64Counter("created_bags_total", metric.WithDescription("The number of bags created per country"))
	country := "unknown"
	labels := []kv.KeyValue{}
	labels = append(labels, metrics.DefaultLabels...)
	labels = append(labels, kv.String("country", country))
	metricCreatedBagsTotal.Add(context.Background(), 1, labels...)

	time.Sleep(time.Second * time.Duration(3))

	metricCreatedBagsTotal = metric.Must(global.Meter("esoptra/pluglet-golang-zaza")).NewFloat64Counter("created_bags_total", metric.WithDescription("The number of bags created per country"))
	country = "unknown2"
	labels = []kv.KeyValue{}
	labels = append(labels, metrics.DefaultLabels...)
	labels = append(labels, kv.String("country", country))
	metricCreatedBagsTotal.Add(context.Background(), 3, labels...)

	time.Sleep(time.Second * time.Duration(3))

	metricCreatedBagsTotal = metric.Must(global.Meter("esoptra/pluglet-golang-zaza")).NewFloat64Counter("created_bags_total", metric.WithDescription("The number of bags created per country"))
	country = "unknown2"
	labels = []kv.KeyValue{}
	labels = append(labels, metrics.DefaultLabels...)
	labels = append(labels, kv.String("country", country))
	metricCreatedBagsTotal.Add(context.Background(), 2, labels...)

	time.Sleep(time.Second * time.Duration(3))

	metricCreatedBagsTotal = metric.Must(global.Meter("esoptra/pluglet-golang-zaza")).NewFloat64Counter("created_bags_total", metric.WithDescription("The number of bags created per country"))
	country = "unknown2"
	labels = []kv.KeyValue{}
	labels = append(labels, metrics.DefaultLabels...)
	labels = append(labels, kv.String("country", country))
	metricCreatedBagsTotal.Add(context.Background(), 2, labels...)

	time.Sleep(time.Second * time.Duration(60))

}
```
Seems to result in sending only the changed metrics in last interval. If is set it to sleep 0 seconds between them (send all at once), it seems to push the correct accumulated values and both metrics (with different labelsets):
```
# TYPE created_bags_total gauge
created_bags_total{application="zaza",cluster="local",country="unknown",minion_ip="127.0.0.1",pluglet_name="test-otel",pluglet_share="1486468616",pluglet_tenant=""} 1
created_bags_total{application="zaza",cluster="local",country="unknown2",minion_ip="127.0.0.1",pluglet_name="test-otel",pluglet_share="1486468616",pluglet_tenant=""} 7
```
It seems to only show the latest send metric in the prometheus exporter.
Should it not be so that the prometheus exporter in the collector retains the previous metrics that came in ?
Prometheus expect metrics to not disappear, so the prom exporter should not clear his cache on every incoming metric.
Or would I need to tell the client somehow to always send ALL metrics (seems overkill), if so, how can I achieve that ?

**Comment by jmacd** [comment] 2020-07-02 17:34
I believe this is a duplicate of #875

**Comment by firefixmaarten** [comment] 2020-07-02 20:10
It seems indeed the same sort of issues, will follow up on those issues, thanks for the pointers

**Comment by MrAlias** [comment] 2020-07-02 21:15
Closing to unify on #875. Please reopen if this is determined to not be a duplicate.

**Closed by MrAlias** 2020-07-02 21:15 UTC
Labels: area: exporter, bug, duplicate
