### ISSUE TITLE
Move b3 under propagation/b3?

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-go#1128] opened 2020-09-07 18:23 UTC
Currently, the B3 propagation implementation is in the trace API. Would it better to move it under propagation/b3 as an implementation of the propagation interfaces? Not many users unless required will depend on B3 and it confuses uses as it's the default propagation format.

**Comment by MrAlias** [comment] 2020-09-08 15:14
Duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/1012 and being addressed in https://github.com/open-telemetry/opentelemetry-go/pull/1118

Please reopen if I've misunderstood.

**Closed by MrAlias** 2020-09-08 15:14 UTC

**Comment by rakyll** [comment] 2020-09-08 18:26
It is a duplicate, sorry for that :)
