### ISSUE TITLE
Getting Started Guide Golang Error on opentelemetry.io

### ISSUE THREAD

**Issue by drichards188** [open-telemetry/opentelemetry-go#2375] opened 2021-11-11 20:35 UTC
Extreme newbie here sorry in advance for mistakes
_____
In the Getting Started guide Docs > Go > Getting Started
https://opentelemetry.io/docs/go/getting-started/

In the second codeblock which details the app.go code for the Fibonacci app, I believe ctx needs to be passed to a.Poll() and a.Write() in the Run func. It is done correctly when we replace Run for the code with instrumentation. But the instructions have us run the Fibonacci app before then which has errors.

Currently
![image](https://user-images.githubusercontent.com/50757879/141364438-a6829014-6258-4c41-af41-2321b80e8311.png)

This works for me
![image](https://user-images.githubusercontent.com/50757879/141364503-189f653f-edda-49e0-9cce-8ed02d06be61.png)

Looks like the code in the actual repo is correct, just isn't updated on the website
https://github.com/open-telemetry/opentelemetry-go/blob/main/example/fib/app.go

Please let me know how to improve issue remarks in the future, or if I can submit PRs for the website or something.

**Comment by MrAlias** [comment] 2021-11-11 20:54
Duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/2323

@chalin how do we sync the docs from this repo upstream. I thought this was an automated process, but I'm guessing I missed something.

**Comment by MrAlias** [comment] 2021-11-11 20:56
> @chalin how do we sync the docs from this repo upstream. I thought this was an automated process, but I'm guessing I missed something.

Ah, looks like we need to update the submodule version https://github.com/open-telemetry/opentelemetry.io/pull/690/files

**Comment by MrAlias** [comment] 2021-11-11 21:59
Created https://github.com/open-telemetry/opentelemetry.io/pull/903 to release the fix in #2323

**Comment by MrAlias** [comment] 2021-11-11 22:07
Changes release. This looks completely resolved now.

![20211111_140656](https://user-images.githubusercontent.com/5543599/141375824-ae4cfad7-fbc2-43af-b549-7ab3aaa05009.png)

**Closed by MrAlias** 2021-11-11 22:07 UTC

**Comment by chalin** [comment] 2021-11-12 17:52
> Ah, looks like we need to update the submodule version https://github.com/open-telemetry/opentelemetry.io/pull/690/files

Right. Thanks for submitting the update!
