### ISSUE TITLE
stdoutmetric should output some bucket information

### ISSUE THREAD

**Issue by david-gang** [open-telemetry/opentelemetry-go#2345] opened 2021-11-04 18:28 UTC
### Problem Statement

A clear and concise description of what the problem is.

I configured the globalmetricsprovider with stdoutmetric and histogram with 101 buckets
```
exporter, err := stdoutmetric.New(stdoutmetric.WithPrettyPrint())
	if err != nil {
		log.Fatalln("failed to initialize metric stdout exporter:", err)
	}
	var boundaries []float64
	for i := 0.0; i <= 1000.0; i += 10 {
		boundaries = append(boundaries, i)
	}
	cont := controller.New(
		processor.NewFactory(
			simple.NewWithHistogramDistribution(histogram.WithExplicitBoundaries(boundaries)),
			exporter,
		),
		controller.WithExporter(exporter),
		controller.WithResource(newResource()),
	)
	if err := cont.Start(context.Background()); err != nil {
		log.Fatalln("failed to start the metric controller:", err)
	}
	global.SetMeterProvider(cont)
```

then i added afterwards a middleware of gin which measures latency:

```
func Logger() gin.HandlerFunc {
	provider := global.GetMeterProvider()
	meter := provider.Meter("gin-middleware")
	requestTimeStat, err := meter.NewInt64Histogram("request-latency")
	if err != nil {
		log.Fatalln("failed to create histogram", err)
	}

	ctx := context.Background()
	return func(c *gin.Context) {
		t := time.Now()
		c.Next()
		latency := time.Since(t).Milliseconds()
		requestTimeStat.Record(ctx, latency)
	}
}
```

The output was lacking all the bucket data and has just

```
	{
		"Name": "request-latency{environment=demo,service.name=coolResource,service.version=v0.1.0,telemetry.sdk.language=go,telemetry.sdk.name=opentelemetry,telemetry.sdk.version=1.1.0,instrumentation.name=gin-middleware}",
		"Sum": 2737
	}
```

I debugged the issue and found out https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/stdout/stdoutmetric/metric.go#L38

```
type line struct {
	Name      string      `json:"Name"`
	Min       interface{} `json:"Min,omitempty"`
	Max       interface{} `json:"Max,omitempty"`
	Sum       interface{} `json:"Sum,omitempty"`
	Count     interface{} `json:"Count,omitempty"`
	LastValue interface{} `json:"Last,omitempty"`

	// Note: this is a pointer because omitempty doesn't work when time.IsZero()
	Timestamp *time.Time `json:"Timestamp,omitempty"`
}

```

the output was missing all bucket info
### Proposed Solution

Could the bucket info be added so all non empty buckets would be printed or if we fear that it would be too much than maybe the first 10 with dots ?
#### Alternatives

Maybe it should be warned somewhere in a log that bucket info is missing

#### Prior Art

A clear and concise list of any similar and existing solutions from other projects that provide context to possible solutions.

**Comment by MrAlias** [comment] 2021-11-11 17:30
Likely duplicate of #954

**Comment by MrAlias** [comment] 2022-05-03 16:50
Duplicate of #954

**Closed by MrAlias** 2022-05-03 16:50 UTC
Labels: duplicate, enhancement
