### ISSUE TITLE
UnmarshalJSON for SpanContext

### ISSUE THREAD

**Issue by gam-phon** [open-telemetry/opentelemetry-go#910] opened 2020-07-06 20:10 UTC
What do you think of providing UnmarshalJSON to ID and SpanID, in api/trace/span_context.go

```
func (t ID) UnmarshalJSON(data []byte) error {
	d, err := IDFromHex(string(data))
        // .... and so on
}
func (s SpanID) UnmarshalJSON(data []byte) error {
         d, err := SpanIDFromHex(string(data))
         // .... and so on
}
```

If you are ok, I can do a pull request

**Comment by MrAlias** [comment] 2020-07-07 23:44
Seems reasonable to me given our existing Marshal methods.

**Comment by gam-phon** [comment] 2020-07-09 08:59
@MrAlias I have created the pull request.
Please let me know if there are changes or comments on the pull request.

**Comment by gam-phon** [comment] 2020-07-11 12:54
I am new to tracing.
I want to propagator trace from service A to service B through a message broker. I was doing marshal in service A for SpanContext then unmarshal in service B to get the SpanContext. After reading the specification, I understand that in http request I should use w3c Trace Context Propagator and the Correlation Context. It serializes SpanContext in special format,`api/trace/trace_context_propagator.go`, in http header through inject in service A then service B will extract the header and return SpanContext. My question why we do not do marshal to SpanContext object to comply with w3c trace context format instead of doing normal marshal. I know that w3c trace context standard is for HTTP headers, but we can use same format to serialize SpanContext. What do you think? for me, I do not think using regular marshal and unmarshal as in the previous pull request to SpanContext will benefit anyone if it does not comply with standard format and since we have standard to serialize SpanContext in special format why we do not use the same format in marshal and unmarshal.

**Comment by MrAlias** [comment] 2020-07-14 19:29
@gam-phon I'm not sure I follow your question.

The W3C trace-context is a standard that specifies a serialized format to propagate  trace-context across service boundaries using (currently only) HTTP. The existing implementation in this repo conforms to the W3C trace-context specification and does so to ensure the compatibility that the specification is intended to offer. This means allowing other systems (possibly not OpenTelemetry) to be interoperable with OpenTelemetry instrumentation.

It sounds like you are proposing a different trace context propagation scheme. If you want to implement your own scheme you should be able to build your own [`Propagator`](https://github.com/open-telemetry/opentelemetry-go/blob/master/api/propagation/propagation.go#L64-L73) and register it with the [global package](https://github.com/open-telemetry/opentelemetry-go/blob/master/api/global/propagation.go#L29-L32). Though you will only be compatible with other things you have also used your propagation scheme on.

**Comment by gam-phon** [comment] 2020-07-14 22:49
@MrAlias I did not mean to create a custom propagator that is not following W3C, What I meant is to use W3C trace-context format in marshal and  unmarshal.

W3C trace-context serialize to
```
("^(?P<version>[0-9a-f]{2})-(?P<traceID>[a-f0-9]{32})-(?P<spanID>[a-f0-9]{16})-(?P<traceFlags>[a-f0-9]{2})(?:-.*)?$")
```
In marshal and  unmarshal functions for SpanContext why we do not use same serialization format as W3C instead of 
```
{"TraceID": "...", "SpanID": "...", "TraceFlags": ...}`
```

I know that W3C trace-context is specific for HTTP now. But now it is only supports HTTP and this is a custom format that is following W3C.

Do you think people will use this format
```
{"TraceID": "...", "SpanID": "...", "TraceFlags": ...}`
```
for sharing context. I do not think so maybe they prefer to share things like this
```
("^(?P<version>[0-9a-f]{2})-(?P<traceID>[a-f0-9]{32})-(?P<spanID>[a-f0-9]{16})-(?P<traceFlags>[a-f0-9]{2})(?:-.*)?$")
```
for something that does not use HTTP.

I am using Redis stream. I prefer to serialize contextSpan in messages like w3c format not like `{"TraceID": "...", "SpanID": "...", "TraceFlags": ...}`

What do you think? Maybe there is another way.
What is the use case for marshal and  unmarshal in this format: `{"TraceID": "...", "SpanID": "...", "TraceFlags": ...}`

**Comment by MrAlias** [comment] 2020-07-16 17:30
If you are (de)serializing a trace ID, span ID, or trace flags in to/out of a `struct` you would want them to work depending on how you define the `struct`. If you abstract these values into a unified trace-context no matter what the user defined it would not be expected behaviour not very useful.

So if my struct is:

```
	var Payload struct {
		TraceID trace.ID `json:"ID"`
		SpanID trace.SpanID `json:"SpanID"`
		Flags string `json:"TraceFlags"`
	}
```
when I unmarshal into that structure I would expect each of those fields to be correctly populated with each of their corresponding values, not a combined trace context.

If you wanted to have a struct like:

```
	var Payload struct {
		TraceContext trace.TraceContext `json:"tracecontext"`
	}
```

It would make sense that the `TraceContext` object should support deserialization in the format you describe. Though it would also require a refactor of the `TraceContext` to store information and provide broader support. In #391 it was proposed to depend on another implementation of the trace-context that had this type of structure. It might be time to investigate that closer. I'll add it to the agenda for today's SIG meeting.

Another thing to consider is the W3C trace-context group has recently started a binary protocol working sub-group. They are looking a developing a binary form of the trace-context and have it supported in a broad set of situations. Are you a part of the redis development at all? It would be useful to support redis in that project (seems like it would be out of scope to develop that support in this project).

**Comment by gam-phon** [comment] 2020-07-16 20:39
@MrAlias Yes I agree with you it will confuse others since it is not the expected behaviour. #391 is exactly what I am looking for.

[Trace Context: binary protocol](https://w3c.github.io/trace-context-binary/) is great. Maybe this package [lightstep/tracecontext.go](https://github.com/lightstep/tracecontext.go), or others, then can support the binary and the text format as well.

**Comment by tmc** [comment] 2020-08-01 00:44
What's holding this up?

**Comment by MrAlias** [comment] 2020-09-25 19:26
Closing as it looks like the TraceContext binary protocol resolved the initial question.

**Closed by MrAlias** 2020-09-25 19:26 UTC
Labels: area:trace, enhancement, pkg:SDK
