### ISSUE TITLE
Add option to set environment for tracer

### ISSUE THREAD

**Issue by Oliveirakun** [open-telemetry/opentelemetry-go#1053] opened 2020-08-11 20:17 UTC
The sdktracer example doesn't show an option to set the environment (production, staging, test, etc.). I have an otlp-collector configured to send data to elastic apm, and didn't find a way to set environment, I've tried using Kv pairs in resource but it didn't work. 
Seems like it doesn't work, and if it works an example or documentation would be nice to avoid this problem to happen for other users.

**Comment by MrAlias** [comment] 2020-08-11 20:57
> I've tried using Kv pairs in resource but it didn't work.

Can you include what you have tried? Setting an attribute in a `Resource` should be propagated to the collector.

**Comment by Oliveirakun** [comment] 2020-08-11 22:45
I've tried all these values, but no one worked:
```golang
sdktrace.WithResource(resource.New(
    kv.Key("service.name").String("foo"),
    kv.Key("environment").String("staging"),
))

sdktrace.WithResource(resource.New(
    kv.Key("service.name").String("foo"),
    kv.Key("service.environment").String("staging"),
))

sdktrace.WithResource(resource.New(
    kv.Key("service.name").String("foo"),
    kv.Key("elastic.apm.environment").String("staging"),
))
```
Only the service name is displayed correclty in APM dashboard

**Comment by MrAlias** [comment] 2020-08-11 23:22
There have been other issues with translations in the collector in the past and I wonder if that is the issue here. Can you verify that the Resource attributes do or do not show up if you use another collector exporter like the logging exporter?

Looking at that exporter it seems like it should correctly handle Resource attributes: 

https://github.com/open-telemetry/opentelemetry-collector/blob/e68440edbb0f2868df9331a5328816270b400951/exporter/loggingexporter/logging_exporter.go#L47-L56

If that does output the expected attributes it would follow that the error would be in the collector in the elastic apm exporter.

**Comment by MrAlias** [comment] 2020-08-20 16:14
@Oliveirakun I'm going to close this as it doesn't seem to be an issue with this repo (I'm not able to reproduce those labels not showing up when set on a resource).

If you're still having this issue and think it's related to this project and you re-open this with some steps to reproduce the issue?

**Closed by MrAlias** 2020-08-20 16:14 UTC
Labels: pkg:example, question
