### ISSUE TITLE
[docs] otel exporter README code examples out of date

### ISSUE THREAD

**Issue by lizthegrey** [open-telemetry/opentelemetry-go#1609] opened 2021-02-26 18:07 UTC
https://github.com/open-telemetry/opentelemetry-go/blob/v0.17.0/exporters/otlp/README.md mentions WithTLSCredentials but that's actually in the otelgrpc options.go package these days, which is confusing because users might expect to use otlp.WithTLSCredentials.

we should either alias these things so that otlp.WithTLSCredentials = otelgrpc.WithTLSCredentials, or we should update the docs.

**Comment by Aneurysm9** [comment] 2021-02-26 18:33
The docs were updated in #1513 and that code is now in an example test that will ensure they stay up-to-date.  We discussed shipping a `v0.18.0` release at the SIG meeting yesterday, we should probably make that happen today.

**Comment by MrAlias** [comment] 2021-02-26 20:12
Closing, duplicate of #1513

**Closed by MrAlias** 2021-02-26 20:12 UTC
Labels: duplicate

**Comment by lizthegrey** [comment] 2021-02-26 20:13
oh, amazing, thank you!
