### ISSUE TITLE
Move mock span or trace out of internal package

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-go#1033] opened 2020-08-05 02:22 UTC
`MockSpan` and `MockTracer` are on the internal package that cannot be used by other repo.

It's not convenient for those third-party repos to add the unit test. Also, [go-contrib](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/v0.10.0/internal/trace) have the same package named `internal/trace` and the functionality of the code is almost the same.

Therefore, maybe we should move `MockSpan` and `MockTracer` out of the internal package and reuse those parts of codes?

**Comment by MrAlias** [comment] 2020-08-05 19:31
This is likely a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/872

**Comment by jmacd** [comment] 2020-08-06 17:18
This looks like not quite a duplicate, since it's about tracing and #872 is about metrics.

**Closed** 2020-09-01 15:16 UTC
Labels: help wanted, pkg:testing, priority:p1, release:required-for-ga
