### ISSUE TITLE
Upgrade Metrics to OTLP v0.5

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-go#1177] opened 2020-09-14 22:56 UTC
The OTLP exporter in this repository is still at version 0.3.  To bring it forward to v0.5 will require two new supports to be in place. 

1. LastValue aggregation is required: being added in #1165. 
2. Histogram aggregation is required: no open PR

Histogram aggregation is required as an alternative to Summary data points.  Since Summary has no current expression in OTLP v0.5, and at the specification level we are leaning in the direction of Histogram or Histogram-like-Sketch as the default aggregation for ValueRecorder instruments, moving this repository to v0.5 with Histogram implemented for ValueRecorder is the closest we can get to the specification.

After LastValue and Histogram support are added _at the current protocol version_, the exporter can be upgraded to v0.5.

**Comment by MrAlias** [comment] 2020-09-15 14:40
Is this a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/1123?

**Comment by jmacd** [comment] 2020-09-15 15:21
Yes, except I've put in more detail about how I think it should be sequenced.

**Comment by MrAlias** [comment] 2020-10-01 15:54
I've updated the description of #1123 to include the information included here and going to close this to resolve the duplicity.

**Closed by MrAlias** 2020-10-01 15:54 UTC
Labels: area:metrics
