### ISSUE TITLE
go.opentelemetry.io/otel/label lost in v0.20.0 and moved. Cannot use a NewInt64Counter due to this blocking error

### ISSUE THREAD

**Issue by anthonyangelo** [open-telemetry/opentelemetry-go#1976] opened 2021-06-08 17:22 UTC
Team, I noticed this `error module go.opentelemetry.io/otel@latest found (v0.20.0), but does not contain package go.opentelemetry.io/otel/label` when trying to set a `NewInt64Counter`. I believe there's a packaging problem here: `https://pkg.go.dev/go.opentelemetry.io/otel`.  Any ideas when that will get fixed ? Label was last seen in `v0.17.0` but got lost after that.

**Comment by Aneurysm9** [comment] 2021-06-08 18:16
That package was renamed to `go.opentelemetry.io/otel/attribute` in [`v0.18.0`](https://github.com/open-telemetry/opentelemetry-go/blob/main/CHANGELOG.md#changed-3).  There have been a number of backward-incompatible changes made.  The [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-go/blob/main/CHANGELOG.md) file should be consulted during updates to ensure you are aware of what has changed.

**Comment by MrAlias** [comment] 2021-06-08 18:16
Duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/1624

The `label` package was renamed to `attribute`: https://github.com/open-telemetry/opentelemetry-go/pull/1541

**Closed by Aneurysm9** 2021-06-08 18:16 UTC
Labels: bug
