### ISSUE TITLE
go get -u go.opentelemetry.io fails

### ISSUE THREAD

**Issue by ngadre-juniper** [open-telemetry/opentelemetry-go#1143] opened 2020-09-09 09:03 UTC
Hi, 

I am using go-redis package which uses the opentelemetry package.

I tried fetching go-redis using "go get -u -v github.com/go-redis/redis"

_[The -u flag instructs get to use the network to update the named packages and their dependencies. By default, get uses the network to check out missing packages but does not use it to look for updates to existing packages.

The -v flag enables verbose progress and debug output.]_

root@bng-hb-dev-03:/homes/ngadre/go/src/github.com# go get -u -v github.com/go-redis/redis
github.com/go-redis/redis (download)
github.com/cespare/xxhash (download)
github.com/dgryski/go-rendezvous (download)
package go.opentelemetry.io/otel/api/global: unrecognized import path "go.opentelemetry.io/otel/api/global": https fetch: Get "https://go.opentelemetry.io/otel/api/global?go-get=1": dial tcp 216.239.32.21:443: i/o timeout
package go.opentelemetry.io/otel/api/metric: unrecognized import path "go.opentelemetry.io/otel/api/metric": https fetch: Get "https://go.opentelemetry.io/otel/api/metric?go-get=1": dial tcp 216.239.32.21:443: i/o timeout
get "golang.org/x/exp/rand": found meta tag get.metaImport{Prefix:"golang.org/x/exp", VCS:"git", RepoRoot:"https://go.googlesource.com/exp"} at //golang.org/x/exp/rand?go-get=1
get "golang.org/x/exp/rand": verifying non-authoritative meta tag
golang.org/x/exp (download)
package go.opentelemetry.io/otel/label: unrecognized import path "go.opentelemetry.io/otel/label": https fetch: Get "https://go.opentelemetry.io/otel/label?go-get=1": dial tcp 216.239.32.21:443: i/o timeout
root@bng-hb-dev-03:/homes/ngadre/go/src/github.com#

I tried separately getting the opentelemetry package but seem to hit the issue #90. 
root@bng-hb-dev-03:/homes/ngadre/go/src/github.com# go get -u go.opentelemetry.io
package go.opentelemetry.io: unrecognized import path "go.opentelemetry.io": https fetch: Get "https://go.opentelemetry.io/?go-get=1": dial tcp 216.239.32.21:443: i/o timeout

Please suggest any workaround.

**Comment by Aneurysm9** [comment] 2020-09-09 16:11
This appears to be a failure connecting to the go.opentelemetry.io vanity domain to retrieve the module metadata.  I am not able to reproduce at this time.  Are you still experiencing this issue?

**Comment by MrAlias** [comment] 2020-10-01 15:56
Closing as this looks like a transient issue and we are not able to reproduce. Please reopen if there is more info to be added to help debug this.

**Closed by MrAlias** 2020-10-01 15:56 UTC
Labels: question, response needed

**Comment by yajna-pandith** [comment] 2020-10-17 19:10
same issue

**Comment by juanandresgs** [comment] 2020-10-28 21:10
same
