### ISSUE TITLE
Metrics SDK global labels

### ISSUE THREAD

**Issue by frycm** [open-telemetry/opentelemetry-go#3349] opened 2022-10-17 18:10 UTC
### Problem Statement

It would be great to have API to configure "global" labels for the all metrics produced from the application. In previous versions it was possible by default resource but now there is no easy way ho to achieve it.
For custom metrics it could be implemented by per metric (but a not too easy way), for external metrics its impossible now.

### Proposed Solution

Extension of View API to allow add attributes to metrics.

**Comment by MrAlias** [comment] 2022-10-17 18:27
Metrics are still associated with a single resource:

https://github.com/open-telemetry/opentelemetry-go/blob/1cbd4c2b7726ded5e7a9a18997cb25977137a0b1/sdk/metric/metricdata/data.go#L28-L33

Is this not suffient?

Is this specifically talking about the prometheus exporter? I.e. this issue? https://github.com/open-telemetry/opentelemetry-go/issues/3166

**Comment by frycm** [comment] 2022-10-17 18:37
Yes, it's mainly about Prometheus exporter. I will check API you mentioned.

**Comment by MrAlias** [comment] 2022-10-17 20:34
> Yes, it's mainly about Prometheus exporter. I will check API you mentioned.

Sounds good. I'm going to close this as it is a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/3166.

**Closed by MrAlias** 2022-10-17 20:34 UTC
Labels: duplicate, enhancement

**Comment by frycm** [comment] 2022-10-19 18:00
At the end I was able to solve it by:

    registry = prometheus.NewRegistry()
    registerer = prometheus.WrapRegistererWith(prometheus.Labels{"...": ...}, registry)
    registerer.Register(exporter.Collector)

**Comment by fracasula** [comment] 2023-01-20 10:46
How come this was closed? It doesn't seem to be solved in #3166 either, right?

```go
func newResource(svcName string) *resource.Resource {
	r, _ := resource.Merge(
		resource.Default(),
		resource.NewWithAttributes(
			semconv.SchemaURL,
			semconv.ServiceNameKey.String(svcName),
			semconv.ServiceVersionKey.String("v0.1.0"),
			attribute.String("environment", "demo"),
			attribute.Int64("ID", 123),
		),
	)
	return r
}
```

I cannot see `environment=demo` and `ID=123` on Prometheus. I see them in the traces on Jaeger though.
How can I get global labels for all metrics via the OpenTelemetry SDK without passing through the Prometheus client? Is there a way? Thanks.

**Comment by fracasula** [comment] 2023-01-24 13:38
@MrAlias any insights?

**Comment by MrAlias** [comment] 2023-01-24 15:49
@fracasula please open a [new issue](https://github.com/open-telemetry/opentelemetry-go/issues/new?assignees=&labels=bug&template=bug_report.md&title=) to address your issue.

**Comment by oto313** [comment] 2025-03-21 13:42
Any progress. I still see the issue  @fracasula mentioned
