### ISSUE TITLE
Add support for `grpc-trace-bin` propagator

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-go#1018] opened 2020-07-31 21:54 UTC
See https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md

**Comment by jmacd** [comment] 2020-08-06 17:21
I wonder if someone on the gRPC team would be willing to contribute this support? @mtwo

**Comment by MrAlias** [comment] 2020-08-24 20:11
possible duplicate of #628

**Comment by MrAlias** [comment] 2020-08-24 20:14
Closing in favor of #628

**Closed by MrAlias** 2020-08-24 20:14 UTC
Labels: area:propagators, duplicate, enhancement
